{
	"Properties": {
		"PRODUCTID": "#Control:ProductID/#Value",
		"SHELFQTY": "#Control:ShelfQty/#Value",
		"STOREID": "#Control:StoreID/#Value"
	},
	"Target": {
		"EntitySet": "StoreItem",
		"ReadLink": "{@odata.readLink}",
		"Service": "/ShopA/Services/ShopA.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}